# POST http://localhost:3000/auth/signup 
# Content-Type: application/json

# { 
#   "name":"pranit",
#   "username":"pranit1221", 
#   "email":"pranit1221@gmail.com",  
#   "password":"Demo123*"  
# }

# POST http://localhost:3000/auth/login 
# Content-Type: application/json

# { 
#   "email":"demo2@gmail.com",  
#   "password":"Demo123*"  
# }

# GET http://localhost:3000/user/search-users
# Content-Type: application/json
# Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY1ZDNhZTQ1OWI4Mzg5YTNkOGU1ODk4YyIsImlhdCI6MTcwODYxNzYxOX0.WRZ2wVegFvJBhiATFdK1FAjyIyAMoL2fPQWDI5OOWzk

# {
#   "query":"test"
# }

# POST http://localhost:3000/chat
# Content-Type: application/json
# Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY1ZDNhZTQ1OWI4Mzg5YTNkOGU1ODk4YyIsImlhdCI6MTcwODYxNzYxOX0.WRZ2wVegFvJBhiATFdK1FAjyIyAMoL2fPQWDI5OOWzk

# {
#   "ReceiverUser":"65d75ac299ca3554b9e9d4c2"
# }

# GET http://localhost:3000/chat
# Content-Type: application/json
# Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY1ZDNhZTQ1OWI4Mzg5YTNkOGU1ODk4YyIsImlhdCI6MTcwODYxNzYxOX0.WRZ2wVegFvJBhiATFdK1FAjyIyAMoL2fPQWDI5OOWzk

# POST http://localhost:3000/chat/group
# Content-Type: application/json
# Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY1ZDNhZTQ1OWI4Mzg5YTNkOGU1ODk4YyIsImlhdCI6MTcwODYxNzYxOX0.WRZ2wVegFvJBhiATFdK1FAjyIyAMoL2fPQWDI5OOWzk

# {
#   "chatName":"testGroup11",
#   "groupAdmin":"pranit",
#   "users":[
#     "65d3ae459b8389a3d8e5898c",
#     "65d51bee21a4f34e8f64ad7c",
#     "65d51cf93542f4c097c1c395",
#     "65d51eb5d03731470f7a878b"
#   ]
# }


PUT http://localhost:3000/chat/group/rename
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY1ZDNhZTQ1OWI4Mzg5YTNkOGU1ODk4YyIsImlhdCI6MTcwODYxNzYxOX0.WRZ2wVegFvJBhiATFdK1FAjyIyAMoL2fPQWDI5OOWzk

{
  "chatName":"Test Group 22222",
  "groupId":"65db5e34bd5f66eeddfcef7b",
}