# POST http://localhost:3000/auth/signup 
# Content-Type: application/json

# { 
#   "name":"Pranit Patil",
#   "username":"@pranit123", 
#   "email":"pranit123@gmail.com",  
#   "password":"Demo123*"  
# }

# POST http://localhost:3000/auth/login 
# Content-Type: application/json

# { 
#   "email":"demo2@gmail.com",  
#   "password":"Demo123*"  
# }

# GET http://localhost:3000/user/search-users
# Content-Type: application/json
# Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY1ZDNhZTQ1OWI4Mzg5YTNkOGU1ODk4YyIsImlhdCI6MTcwODYxNzYxOX0.WRZ2wVegFvJBhiATFdK1FAjyIyAMoL2fPQWDI5OOWzk

# {
#   "query":"test"
# }

# POST http://localhost:3000/chat
# Content-Type: application/json
# Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY1ZGUzNWJkNzljY2E5NzQ5ZjMzZWRjZSIsImlhdCI6MTcwOTA2MTU2NX0.VlQWH9pZqTFky8CeUlLhn-ffKDdCQIZtq07V6WeMPTs

# {
#   "ReceiverUser":"65de35fd79cca9749f33edd0"
# }

# GET http://localhost:3000/chat
# Content-Type: application/json
# Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY1ZDNhZTQ1OWI4Mzg5YTNkOGU1ODk4YyIsImlhdCI6MTcwODYxNzYxOX0.WRZ2wVegFvJBhiATFdK1FAjyIyAMoL2fPQWDI5OOWzk

# POST http://localhost:3000/chat/group
# Content-Type: application/json
# Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY1ZGUzNWJkNzljY2E5NzQ5ZjMzZWRjZSIsImlhdCI6MTcwOTA2MTU2NX0.VlQWH9pZqTFky8CeUlLhn-ffKDdCQIZtq07V6WeMPTs

# {
#   "chatName":"myChatGrp",
#   "groupAdmin":"pranit",
#   "users":[
#     "65de35fd79cca9749f33edd0",
#     "65de360b79cca9749f33edd2",
#     "65de361779cca9749f33edd4",
#     "65de362a79cca9749f33edd6"
# ]
# }


# PUT http://localhost:3000/chat/group/rename
# Content-Type: application/json
# Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY1ZGUzNWJkNzljY2E5NzQ5ZjMzZWRjZSIsImlhdCI6MTcwOTA2MTU2NX0.VlQWH9pZqTFky8CeUlLhn-ffKDdCQIZtq07V6WeMPTs

# {
#   "chatName":"pranit1",
#   "groupId":"65df33705d0aba56b3366876"
# }

# GET http://localhost:3000/chat
# Content-Type: application/json
# Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY1ZGUzNWJkNzljY2E5NzQ5ZjMzZWRjZSIsImlhdCI6MTcwOTA2MTU2NX0.VlQWH9pZqTFky8CeUlLhn-ffKDdCQIZtq07V6WeMPTs


# PUT  http://localhost:3000/chat/group/add
# Content-Type: application/json
# Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY1ZGUzNWJkNzljY2E5NzQ5ZjMzZWRjZSIsImlhdCI6MTcwOTA2MTU2NX0.VlQWH9pZqTFky8CeUlLhn-ffKDdCQIZtq07V6WeMPTs

# {
#   "userId":"65df38324ad366bff5db9a69",
#   "chatId":"65df33705d0aba56b3366876"
# }

POST http://localhost:3000/user/get-profile
Content-Type: application/json

{
  "username":"@pranit123"
}
